---
title: portfolio-samples
description: a selection of technical writing examples
url: https://firoyj.github.io/portfolio-samples/docs/
remote_theme: pages-themes/midnight@v0.2.0
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  coderay:
    line_numbers: false
    tab_width: 2
    css: style

lsi: false
safe: true
source: portfolio-directory
incremental: false
highlighter: rouge
gist:
  noscript: false
---
